Repository CVDS-ECI/ECI-Biblioteca, pull requests merged in 2019-11, with the labels that each got.

#5 Inicio de Sesion
  README.md
  img/Diagrama_de_clases.png
  src/main/java/edu/eci/cvds/managedbeans/PruebaBean.java
  src/main/java/edu/eci/cvds/managedbeans/ShiroBean.java
  src/main/webapp/WEB-INF/shiro.ini
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/login.xhtml
Labels: enhancement

#8 Aplicacion
  ScriptsSQL/CrearyPoblar.sql
  src/main/java/edu/eci/cvds/entities/Recurso.java
  src/main/java/edu/eci/cvds/persistence/RecursoDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/MyBatisRecursoDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/mappers/RecursoMapper.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/mappers/UsuarioMapper.java
  src/main/java/edu/eci/cvds/services/BibliotecaServices.java
  src/main/java/edu/eci/cvds/services/impl/BibliotecaServicesImpl.java
  src/main/resources/mappers/RecursoMapper.xml
  src/main/resources/mappers/UsuarioMapper.xml
Labels: enhancement

#10 Actualizando Front con Aplicación
  ScriptsSQL/CrearyPoblar.sql
  src/main/java/edu/eci/cvds/entities/Recurso.java
  src/main/java/edu/eci/cvds/persistence/RecursoDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/MyBatisRecursoDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/mappers/RecursoMapper.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/mappers/UsuarioMapper.java
  src/main/java/edu/eci/cvds/services/BibliotecaServices.java
  src/main/java/edu/eci/cvds/services/impl/BibliotecaServicesImpl.java
  src/main/resources/mappers/RecursoMapper.xml
  src/main/resources/mappers/UsuarioMapper.xml
Labels: enhancement

#16 BugFix de auto registrar recurso en vista y Si no existe una sesión a…
  src/main/java/edu/eci/cvds/managedbeans/AdminBean.java
  src/main/java/edu/eci/cvds/managedbeans/ShiroBean.java
  src/main/java/edu/eci/cvds/security/ApacheShiroLogin.java
  src/main/java/edu/eci/cvds/security/OnlyNotAutenticated.java
  src/main/webapp/WEB-INF/shiro.ini
  src/main/webapp/admin/paginas/registrarRecurso.xhtml
Labels: bugFix

#20 registrar recurso pruebas
  src/main/java/edu/eci/cvds/services/BibliotecaException.java
  src/test/java/edu/eci/cvds/test/ServicesBibliotecaTest.java
Labels: enhancement

#21 #3 Cambiar estado de un recuros; actualizar dao y mybatis Dao
  src/main/java/edu/eci/cvds/persistence/RecursoDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/MyBatisRecursoDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/mappers/RecursoMapper.java
Labels: Extensión, enhancement

#32 Admin
  src/main/java/edu/eci/cvds/managedbeans/AdminBean.java
  src/main/webapp/admin/paginas/recursos.xhtml
  src/main/webapp/admin/paginas/registrarRecurso.xhtml
Labels: bugFix, enhancement

#43 pruebas corregidas
  src/test/java/edu/eci/cvds/test/ServicesBibliotecaTest.java
Labels: bugFix

#46 Front
  src/main/java/edu/eci/cvds/managedbeans/AdminBean.java
  src/main/webapp/WEB-INF/include/templateAdmin.xhtml
  src/main/webapp/adminInicio.xhtml
  src/main/webapp/registrarRecurso.xhtml
  src/main/webapp/resources/js/initiative.js
Labels: bugFix, enhancement

#51 Correcciones generales y agregando template a horario
  pom.xml
  src/main/java/edu/eci/cvds/test/ServicesBibliotecaTest.java
  src/main/resources/mappers/RecursoMapper.xml
  src/main/webapp/WEB-INF/shiro.ini
  src/main/webapp/admin/paginas/dashboard.html
  src/main/webapp/admin/paginas/recursos.html
  src/main/webapp/admin/paginas/recursos.xhtml
  src/main/webapp/admin/paginas/registrarRecurso.html
  src/main/webapp/admin/paginas/registrarRecurso.xhtml
  src/main/webapp/comunidadInicio.xhtml
  src/main/webapp/reservaRecursos.xhtml
  src/main/webapp/resources/js/initiative.js
  src/test/java/edu/eci/cvds/test/ServicesBibliotecaTest.java
  tables.sql
Labels: Extensión, enhancement

#52 Aplicacion
  parcial-2.pdf
  pom.xml
  src/main/java/edu/eci/cvds/entities/Reserva.java
  src/main/java/edu/eci/cvds/entities/TipoReserva.java
  src/main/java/edu/eci/cvds/managedbeans/ComunidadBean.java
  src/main/java/edu/eci/cvds/managedbeans/ScheduleBean.java
  src/main/java/edu/eci/cvds/test/ServicesBibliotecaTest.java
  src/main/resources/mappers/RecursoMapper.xml
  src/main/webapp/401.html
  src/main/webapp/404.html
  src/main/webapp/WEB-INF/shiro.ini
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/admin/paginas/dashboard.html
  src/main/webapp/admin/paginas/recursos.html
  src/main/webapp/admin/paginas/recursos.xhtml
  src/main/webapp/admin/paginas/registrarRecurso.html
  src/main/webapp/admin/paginas/registrarRecurso.xhtml
  src/main/webapp/comunidadInicio.xhtml
  src/main/webapp/registrarRecurso.xhtml
  src/main/webapp/reservaRecursos.xhtml
  src/main/webapp/resources/js/initiative.js
  src/test/java/edu/eci/cvds/test/ServicesBibliotecaTest.java
  tables.sql
Labels: Extensión, bugFix, enhancement

#53 Front
  src/main/java/edu/eci/cvds/entities/Recurso.java
  src/main/java/edu/eci/cvds/entities/Reserva.java
  src/main/java/edu/eci/cvds/managedbeans/ComunidadBean.java
  src/main/java/edu/eci/cvds/managedbeans/ReservaBean.java
  src/main/java/edu/eci/cvds/persistence/ReservaDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/MyBatisReservaDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/mappers/ReservaMapper.java
  src/main/java/edu/eci/cvds/services/BibliotecaServices.java
  src/main/java/edu/eci/cvds/services/impl/BibliotecaServicesImpl.java
  src/main/resources/mappers/ReservaMapper.xml
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/comunidadInicio.xhtml
  src/main/webapp/reservaRecursos.xhtml
  src/main/webapp/resources/bootstrap-datetimepicker-0/css/bootstrap-datetimepicker.min.css
  src/main/webapp/resources/bootstrap-datetimepicker-0/js/bootstrap-datetimepicker.min.js
  src/test/java/edu/eci/cvds/test/ServicesBibliotecaTest.java
Labels: enhancement

#60 Tarea7
  src/main/java/edu/eci/cvds/entities/EstadoReserva.java
  src/main/java/edu/eci/cvds/entities/Reserva.java
  src/main/java/edu/eci/cvds/managedbeans/ReservaBean.java
  src/main/java/edu/eci/cvds/persistence/ReservaDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/MyBatisReservaDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/mappers/ReservaMapper.java
  src/main/java/edu/eci/cvds/services/BibliotecaServices.java
  src/main/java/edu/eci/cvds/services/impl/BibliotecaServicesImpl.java
  src/main/resources/mappers/ReservaMapper.xml
  src/main/webapp/Expropiado.xhtml
  src/main/webapp/Servicios Academicos - Plan de estudios.html
  src/main/webapp/WEB-INF/shiro.ini
  src/main/webapp/adminInicio.xhtml
  src/main/webapp/clonado.xhtml
  src/main/webapp/comunidadInicio.xhtml
  src/main/webapp/recursosDisponibles.xhtml
  src/main/webapp/reservaRecursos.xhtml
  src/main/webapp/reservaRecursosA.xhtml
  src/main/webapp/reservaRecursosC.xhtml
  src/main/webapp/reservaRecursosN.xhtml
  src/test/java/edu/eci/cvds/test/ServicesBibliotecaTest.java
Labels: Extensión, enhancement
