Repository CVDS-ECI/ECI-Biblioteca, pull requests merged in 2019-12, with the labels that each got.

#62 Tarea 8
  src/main/java/edu/eci/cvds/entities/Reserva.java
  src/main/java/edu/eci/cvds/entities/Usuario.java
  src/main/java/edu/eci/cvds/managedbeans/ReservaBean.java
  src/main/java/edu/eci/cvds/persistence/UsuarioDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/MyBatisReservaDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/MyBatisUsuarioDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/mappers/UsuarioMapper.java
  src/main/java/edu/eci/cvds/services/BibliotecaServices.java
  src/main/java/edu/eci/cvds/services/impl/BibliotecaServicesImpl.java
  src/main/resources/mappers/ReservaMapper.xml
  src/main/resources/mappers/UsuarioMapper.xml
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/comunidadInicio.xhtml
  src/main/webapp/reservaRecursosA.xhtml
  src/main/webapp/reservaRecursosC.xhtml
  src/main/webapp/reservaRecursosN.xhtml
  src/test/java/edu/eci/cvds/test/ServicesBibliotecaTest.java
Labels: Extensión, bugFix, enhancement

#63 Tarea 8
  src/main/java/edu/eci/cvds/managedbeans/ReservaBean.java
Labels: Extensión, bugFix, enhancement

#64 Tarea 8
  src/main/java/edu/eci/cvds/entities/Reserva.java
  src/main/java/edu/eci/cvds/managedbeans/ReservaBean.java
  src/main/java/edu/eci/cvds/persistence/ReservaDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/MyBatisReservaDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/mappers/ReservaMapper.java
  src/main/java/edu/eci/cvds/services/BibliotecaServices.java
  src/main/java/edu/eci/cvds/services/impl/BibliotecaServicesImpl.java
  src/main/resources/mappers/ReservaMapper.xml
  src/main/webapp/reservaRecursosA.xhtml
  src/main/webapp/reservaRecursosC.xhtml
  src/main/webapp/reservaRecursosN.xhtml
Labels: Extensión, bugFix, enhancement

#61 Reportedeocupación
  Manual de usuario Ecibrary.docx
  ScriptsSQL/CrearyPoblar.sql
  ScriptsSQL/consultas Reporte de ocupación
  src/main/java/edu/eci/cvds/entities/Reserva.java
  src/main/java/edu/eci/cvds/entities/TipoReserva.java
  src/main/java/edu/eci/cvds/guice/GuiceContextListener.java
  src/main/java/edu/eci/cvds/managedbeans/DropdownView.java
  src/main/java/edu/eci/cvds/managedbeans/ReporteBean.java
  src/main/java/edu/eci/cvds/managedbeans/graphics/RecursosMasUsados.java
  src/main/java/edu/eci/cvds/managedbeans/graphics/RecursosMasUsadosPorPrograma.java
  src/main/java/edu/eci/cvds/managedbeans/graphics/RecursosMenosUsados.java
  src/main/java/edu/eci/cvds/managedbeans/graphics/ReservasCanceladas.java
  src/main/java/edu/eci/cvds/managedbeans/graphics/ReservasRecurrentes.java
  src/main/java/edu/eci/cvds/persistence/ReporteDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/MyBatisReporteDAO.java
  src/main/java/edu/eci/cvds/persistence/mybatisimpl/mappers/ReporteMapper.java
  src/main/java/edu/eci/cvds/services/BibliotecaServices.java
  src/main/java/edu/eci/cvds/services/BibliotecaServicesFactory.java
  src/main/java/edu/eci/cvds/services/impl/BibliotecaServicesImpl.java
  src/main/resources/mappers/ReporteMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/include/MenuA.xhtml
  src/main/webapp/adminInicio.xhtml
  src/main/webapp/reporteDeOcupacion.xhtml
  src/test/java/edu/eci/cvds/test/GoogleSearchTest.java
  src/test/java/edu/eci/cvds/test/TransaccionIT.java
Labels: Extensión, enhancement

#66 Graficas finalizadas y arregladas :100:
  src/main/java/edu/eci/cvds/managedbeans/graphics/ReservasPorUsuario.java
  src/main/webapp/reporteDeOcupacion.xhtml
Labels: bugFix, enhancement
